version: "3.8"

services:
  backend:
    build: ./backend
    restart: on-failure
    env_file: .env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.data.mongodb.uri" : "$MONGO_URI",
        "spring.data.mongodb.database" : "ansie" }'
    volumes:
      - mavencache:/root/.m2
    healthcheck:
      test: "curl --fail http://localhost:8080/api/examQuestions || exit 1"
      interval: 10s
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    init: true
    restart: on-failure
    ports:
      - 5173:5173

volumes:
  mavencache: